### PR TITLE
Added support for CONFIG_OPTIONS variable

### PR DESCRIPTION
**Pull request by larso**
New version, now docker-entrypoint.sh checks for a CONFIG_OPTIONS variable, expecting a | delimited string with configuration options. I have also updated the README.md file to reflect the change and added an example.

### CODE REVIEW

**Comment by williamboman** [comment]
Hey @larso. First, terribly terribly sorry for not attending to this earlier. I fully understand what you're trying to achieve with this, but I can't help but feel like the idea of splitting on `|` is a bit too hacky to offer official support for it. I think avoiding relying on some special split character would put me more at ease. I have two spontaneous ideas:

1. Support for configuring through environment variables (this would require some more effort, but I'm not concerned about maintenance efforts considering how mature thelounge has become)
1. Configuration expressed in a more structured format. What I mean by this is basically expressing this config through JSON or YAML instead of an environment variable that splits on `|`. Think
```
thelounge:
  environment:
    THELOUNGE_CONFIG: |
      public: true
      https:
        enable: true
```

**Comment by larso** [comment]
Hi @williamboman 
My original PR was what you described in your first proposal. That follows the 12-factor app methodology.
The original conversation can be seen here: https://github.com/thelounge/thelounge-docker/pull/104
Unfortunately, I scratched the original code :-/

Your second proposal seems more elegant though . I'll take a look at it if I get some spare time :+1:

**Comment by williamboman** [comment]
> My original PR was what you described in your first proposal. That follows the 12-factor app methodology.

Ah thanks for linking to the original issue, I agree with your statement that individual environment variables would be neater (like, `THELOUNGE_CONFIG_PUBLIC=true`, `THELOUNGE_CONFIG_HTTPS_ENABLE=false`, etc.). These environment variables would of course be subject to changes between versions, just as `config.js` is, so I'm not concerned about potential drift between env vars and underlying TL config structure. 

I guess the only concerns I would have with this approach would be the sheer amount of env variables to maintain (although as I mentioned in my other comment, there really isn't that much activity upstream so would most likely be a one-time cost).

> Your second proposal seems more elegant though . I'll take a look at it if I get some spare time 👍

Cool! I think it's fundamentally different from the 1st option (env vars), and comes with other complexities. Should it translate the YAML to a set of `--config` options, or should it perhaps do a deep merge of the JSON structure itself on top of the `config.js` and overwrite the file with the new result? I think the latter seems more robust to me

**Comment by larso** [comment]
Closing this pull request

**Pull request closed without merging**
