### PR TITLE
Added support for configuring server through environment variables

### PR DESCRIPTION
**Pull request by larso**
docker-entrypoint.sh has been modified so it injects the correct configuration options given a set of environment variables. The README.md has been modified reflecting these changes.

The environment variables are used through setting the on the command line with docker run -e VARIABLE=value ... or in a Kubernetes deploy config.

### CODE REVIEW

**Comment by xPaw** [comment]
These enviroment variables will get out of sync with the config file for sure. It would be better to have 1 env variable that would pass anything to lounge's `-c`.

**Comment by larso** [comment]
> These enviroment variables will get out of sync with the config file for sure. It would be better to have 1 env variable that would pass anything to lounge's `-c`.

Hmm. I see your point, but most other container distributions use individual variables for individual. osixia/docker-openldap is an example here. 

I guess you are looking for something like CONFIG_ARGUMENTS="host=a|port=9000|ldap.url=ldaps://ldap.example.com"  ?

**Comment by xPaw** [comment]
Space would probably be better, but you would have to take care of the separator in quoted strings.

**Comment by larso** [comment]
> Space would probably be better, but you would have to take care of the separator in quoted strings.

Given that we operate inside a container without the usual tools - that is going to be hairy. I'll send in a seperate merge request with a single CONFIG_OPTIONS argument later today

**Pull request closed without merging**
